### ISSUE TITLE
Support for self-signed certificates

### ISSUE THREAD

**Issue by pedroigor** [stianst/keycloak-tokens-cli#13]
Is it possible to connect to servers using TLS?

The only way I could make it work is by disabling TLS verification by forcing `quarkus.tls.trust-all=true` at build time. Not ideal.

The `quarkus-rest-client` does support configuring TLS programmatically but I don't think the same is true for `quarkus-oidc-client`.

If you think it makes sense, I can send a PR to temporarily enable TLS by trusting any certificate and disabling verifications.

**Comment by stianst** [comment]
You mean self-signed certificates right? TLS should already just work, although haven't tested that.

I'm not a huge fan of disabling verification for TLS, as that more or less renders it useless ;)

Would perhaps be better to have a simple way to add additional certs, and maybe even a simple way to import a cert from a given https URL.

**Comment by stianst** [comment]
TLS works as expected as long as it's not using a self-signed certificate
