### ISSUE TITLE
Revise truststore configuration

### ISSUE THREAD

**Issue by thomasdarimont** [stianst/keycloak-tokens-cli#64]
Currently truststore doesn't work and can only be configured via config file. Manually adding trust store at the "root" in the configuration did not work either. Truststore setting was removed after adding new (http) context.
Truststore configuration does not work, even with truststore set, I cannot access issuers using https.

**Comment by thomasdarimont** [comment]
I think it would be good to allow a trust store per configured issuer.

**Comment by stianst** [comment]
> I think it would be good to allow a trust store per configured issuer.

Won't add that as part of this issue, and not sure I see why that would be needed. If you still think it's worth it, could you open a new issue and explain why?
