### ISSUE TITLE
Cannot fetch userinfo with current token

### ISSUE THREAD

**Issue by thomasdarimont** [stianst/keycloak-tokens-cli#71]
Could not request userinfo with kct. It seems that scope `openid` missing when trying to request userinfo. 
It will even not sent the request.

```
tom@neumann ~/bin
$ kct token --context=acme-internal-http-test-client-ropc --decode
{
"exp" : 1727949995,
"iat" : 1727949695,
"jti" : "282fe846-6538-4dc7-b531-41e8a850ac18",
"iss" : "http://id.acme.test:8080/auth/realms/acme-internal",
"sub" : "376ecd89-db04-4bcb-9e20-f4e0662d1407",
"typ" : "Bearer",
"azp" : "test-client-ropc",
"sid" : "f2a00842-d786-409e-8c35-e24532faf856",
"scope" : "profile email",
"email_verified" : true,
"name" : "Theo Tester",
"preferred_username" : "tester",
"given_name" : "Theo",
"locale" : "en",
"family_name" : "Tester",
"picture" : "https://en.gravatar.com/userimage/52342809/a957ac868585f91edf7eb9b7463328b9.jpeg?size=64",
"email" : "tester@local"
}

tom@neumann ~/bin
$ kct userinfo --context=acme-internal-http-test-client-ropc --scope="profile email"       
Requested scopes must be a subset of configured scopes
```

**Comment by stianst** [comment]
It doesn't request `oidc` scope by default. When creating a context if you want it to be an `oidc` request, then just add `scope=oidc`.

Maybe could be better explained in docs, or a better error message.

**Comment by stianst** [comment]
It needs the `openid` scope and it adds that if missing. However, the problem is that the `scope` passed to commands needs to be a subset of the configured scopes for the context. It should just complain instead of trying to add the scope automatically.
