### ISSUE TITLE
Add option to configure the default context via CLI

### ISSUE THREAD

**Issue by thomasdarimont** [stianst/keycloak-tokens-cli#72]
Currently it doesn't seem possible to set the default context via the CLI. Therefore every command must include `--context`.

**Comment by stianst** [comment]
It is, but maybe it's a bit counter intuitive:

```
kct config update --default-context=mycontext
```

**Comment by stianst** [comment]
Also added a way to set the default context when creating or updating contexts (https://github.com/stianst/keycloak-tokens-cli/issues/77). With that you can just do:

```
kct config context update -c mycontext --default
```
